# Generated by Django 5.1.3 on 2025-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontent',
            name='gravity',
            field=models.CharField(default='start', max_length=20),
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='width',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='books', to='reader.booksection'),
        ),
    ]
