# Generated by Django 4.2.4 on 2023-09-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
