# Generated by Django 4.2.4 on 2023-09-28 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_material_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='upload_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
