# Generated by Django 4.2.5 on 2023-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_material_upload_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.FileField(blank=True, null=True, upload_to='courses/outlines/'),
        ),
    ]
