# Generated by Django 4.2.5 on 2023-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_course_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedissue',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
