# Generated by Django 3.2 on 2023-10-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_flaggedissue_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq', models.FileField(upload_to='pq')),
                ('year', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_questions', to='app.course')),
            ],
        ),
    ]
