# Generated by Django 3.2 on 2024-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240707_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='time',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
