# Generated by Django 5.1.3 on 2024-12-13 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('childrens', models.ManyToManyField(blank=True, related_name='parents', to='blog.blogpage')),
                ('next_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='blog.blogpage')),
                ('previous_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='blog.blogpage')),
            ],
        ),
    ]
