# Generated by Django 5.1.1 on 2024-09-18 14:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
