# Generated by Django 5.1.3 on 2024-12-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_document_tag_blogpage_slug_alter_blogpage_next_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, to='blog.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='alt_text',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
