# Generated by Django 5.1.3 on 2024-12-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_gallery_images_document_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='allow_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covers', to='blog.document'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='blog.tag'),
        ),
    ]
