# Generated by Django 5.1.3 on 2025-01-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicepriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.servicepriority'),
        ),
    ]
