# Generated by Django 5.1.3 on 2025-03-13 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_account_date_of_birth_account_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.FileField(blank=True, default='/media/imgs/default.png', null=True, upload_to='profile'),
        ),
    ]
