# Generated by Django 5.1.3 on 2025-02-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
