# Generated by Django 5.1.1 on 2024-10-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_delete_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastquestion',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
