# Generated by Django 5.1.3 on 2025-01-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
