# Generated by Django 5.1.3 on 2025-01-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_account_name_wallet_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='nin',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
    ]
