# Generated by Django 5.1.3 on 2025-01-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('link_type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('slot', models.IntegerField(default=3)),
                ('available_slot', models.IntegerField(default=0)),
            ],
        ),
    ]
