# Generated by Django 5.1.3 on 2025-01-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FillInTheBlanksQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blanks', models.TextField(help_text='Enter blanks separated by [BLANK]. Example: The capital of [BLANK] is [BLANK].')),
                ('correct_answers', models.TextField(help_text='Enter correct answers separated by commas. Example: Paris, France')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('correct_answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='material.course')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opts', to='cbt.question')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_test', to='material.course')),
                ('essays', models.ManyToManyField(blank=True, to='cbt.essayquestion')),
                ('fill_the_blank', models.ManyToManyField(blank=True, to='cbt.fillintheblanksquestion')),
                ('objectives', models.ManyToManyField(blank=True, to='cbt.question')),
                ('true_false', models.ManyToManyField(blank=True, to='cbt.truefalsequestion')),
            ],
        ),
    ]
