# Generated by Django 3.2 on 2024-08-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FillInTheBlanksQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blanks', models.TextField(help_text='Enter blanks separated by [BLANK]. Example: The capital of [BLANK] is [BLANK].')),
                ('correct_answers', models.TextField(help_text='Enter correct answers separated by commas. Example: Paris, France')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('correct_answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.ManyToManyField(blank=True, to='cbt.Option')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_test', to='material.course')),
                ('essays', models.ManyToManyField(blank=True, to='cbt.EssayQuestion')),
                ('fill_the_blank', models.ManyToManyField(blank=True, to='cbt.FillInTheBlanksQuestion')),
                ('objectives', models.ManyToManyField(blank=True, to='cbt.Question')),
                ('true_false', models.ManyToManyField(blank=True, to='cbt.TrueFalseQuestion')),
            ],
        ),
    ]
