# Generated by Django 3.2 on 2023-10-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_auto_20231003_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to='cbt.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='cbt.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c', to='cbt.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d', to='cbt.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e', to='cbt.option'),
        ),
    ]
