# Generated by Django 3.2 on 2023-10-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0007_essaycourse_essayquestion_essaytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EssayCourse',
        ),
    ]
