# Generated by Django 3.2 on 2023-10-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_delete_essaycourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlanksQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('blanks', models.TextField(help_text='Enter blanks separated by [BLANK]. Example: The capital of [BLANK] is [BLANK].')),
                ('correct_answers', models.TextField(help_text='Enter correct answers separated by commas. Example: Paris, France')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('correct_answer', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cbt.truefalsecourse')),
            ],
        ),
    ]
